//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinalUygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorum()
        {
            this.Siir = new HashSet<Siir>();
        }
    
        public int YorumNo { get; set; }
        public string YorumDetay { get; set; }
        public Nullable<System.DateTime> YorumTarih { get; set; }
        public Nullable<int> KullaniciNo { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siir> Siir { get; set; }
    }
}
